name: GithubSecretDemo
on: [ push ]

jobs:
  githubsecret:
    runs-on: ubuntu-latest
    steps:
      - name : secret-demo 
        run: echo ${{secrets.SECRET_TESTVAL}} 
        #The secret will masked 
      - name : secret-demo-unmasked 
        run: echo ${{secrets.SECRET_TESTVAL}} | sed 's/./& /g'
        #The secret will displayed 
