name: Pull request labeler
on: [ pull_request_target ]

permissions:
  contents: read
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        #This workflow makes use of prewritten action labeler
        #It automatically labels new pull requests based on the paths of files being changed
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }} #Using Github_Token as input parameter