name: Pull request labeler
on: [ pull_request_target ]

permissions:
  contents: read
  pull-requests: write

jobs:
  gosetup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2.2.0
        with:
          token: ${{secrets.SECRET_TOKEN}}
