name : Manual-Trigger-demo
on : repository_dispatch
jobs:
  manual-trigger-demo:       #Name of job
    runs-on: ubuntu-latest  #Name of virtual machine on which job runs
    steps:
      - name: manual-trigger1 #Name of step
        id: job1
        run: |
          pwd
          echo ${{github.event.client_payload.msg}}
