name : branch-condition-demo
on:
  push:
    branches:
      - master
      - 'pr-*' #if branch name matches with at max 1 / in name Eg: pr-fix1/fix1
      - '!pr-**' #can support 2 / - ie., here not equal
    #can also use branches ignore
    tags:
      - v1.*
    paths_ignore : #dont run this workflow if .java file is pushed
      - '**.java'
jobs:
  shell-command-demo:       #Name of job
    runs-on: ubuntu-latest  #Name of virtual machine on which job runs
    steps:
      - name : print-message #Name of step
        run: echo "Hello World" #Command to run
      - name: running-multiline-scripts
        run: |     # Using pipe symbol, we can preserve new line and run multiple commands
          node -v
          npm -v