name : branch-condition-demo
on:
  [push]:
    branches:
      - master
      - 'fix/*' # Trigger any branch starting with fix but doesnt match '/'
      - 'fix/**' #fix/branch/b1 will also be supported
    #can also use branches-ignore if you want to ignore a branch - but cant use branches & branches-ignore together
  tags:
    - v1.*
jobs:
  shell-command-demo:       #Name of job
    runs-on: ubuntu-latest  #Name of virtual machine on which job runs
    steps:
      - name : print-message #Name of step
        run: echo "Hello World" #Command to run
      - name: running-multiline-scripts
        run: |     # Using pipe symbol, we can preserve new line and run multiple commands
          node -v
          npm -v