name : branch-condition-demo
on:
  - push:
    - master
    - pr-fix
jobs:
  shell-command-demo:       #Name of job
    runs-on: ubuntu-latest  #Name of virtual machine on which job runs
    steps:
      - name : print-message #Name of step
        run: echo "Hello World" #Command to run
      - name: running-multiline-scripts
        run: |     # Using pipe symbol, we can preserve new line and run multiple commands
          node -v
          npm -v